### ISSUE TITLE
Time Cheats not working?

### ISSUE THREAD

**Issue by GLiTcH2** [bad1dea/NXCheats#103]
I am not sure if I am doing something wrong but I have Time Stop, Time Resume, Time FF and Time RW. However when I hold ZL and press the Right stick which I assume is what R3Up, R3Down, etc.. is all it does is bring up the purah pad scope?

**Comment by bad1dea** [comment]
> I am not sure if I am doing something wrong but I have Time Stop, Time Resume, Time FF and Time RW. However when I hold ZL and press the Right stick which I assume is what R3Up, R3Down, etc.. is all it does is bring up the purah pad scope?

HOLD ZL + Right Stick Up/Down/Left/Right 

Don't press Right Stick Down.. just move it up/down/left/right..

i.e HOLD ZL + LEFT (Right Stick) to rewind time.

**Comment by GLiTcH2** [comment]
Hmm that doesn't seem to be working, Is it because I am on an Yuzu? I know you said you don't use Emus. Or could it be because I am using a DualShock4 controller? I mean I would assume it would work fine cause the Glider x3 code works but instead of 80000001 for holding A button I changed it to 80000010 which is for me is pressing L stick and it works fine.

**Comment by bad1dea** [comment]
Probably not because it’s an asm hack,
Glider is a pointer hack.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by GLiTcH2** [comment]
Ok I will just use the normal longer days cheats, Thanks!
