### ISSUE TITLE
How does item multiplier work?

### ISSUE THREAD

**Issue by StanTheRebel** [bad1dea/NXCheats#11]

**Comment by bad1dea** [comment]
Pick up item... and it multiplies it.. you must have at least 1 of the item, or you can drop item + pick up

**Comment by epl609** [comment]
None of the multiplayer codes are working for me, individually or all together. Thank you for the great work everything else is perfection.

**Comment by subworx** [comment]
On Yuzu 1420 and game 1.0.0, "#06b Item Multiplier (5x) ★" doesn't work for me either.

Drop one item, and pick one up instead of 5.
