### ISSUE TITLE
TOTK Readme links to non-existent changelog

### ISSUE THREAD

**Issue by damianb** [bad1dea/NXCheats#12]
https://github.com/bad1dea/NXCheats/blob/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom/README.md

links to `./CHANGELOG.md` which of course doesn't exist in the directory.

Could always link to the commit history for the time being, but a 404 is probably not ideal.

**Comment by bad1dea** [comment]
yeah im in the misdle of cleaning out this repo, but got distracted by the leak. itll be cleaned uo and stuff once i get to it.
