### ISSUE TITLE
What does the "Add 60 Seconds To Mission Timer" cheat for TOTK do exactly?

### ISSUE THREAD

**Issue by 2ndHouse** [bad1dea/NXCheats#121]
I'm referring to this code:

https://github.com/bad1dea/NXCheats/tree/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom/0100F2C0115B6000%20v262144%20for%20Yuzu/%2350.%20Add%2060%20Seconds%20To%20Mission%20Timer%20(L3%2BR3)/cheats

I assumed it would add a minute to mini-game timers like picking up the plushies for Juney, but it seems to do nothing but crouch and activate my scope (the default actions for L3 and R3). Maybe I'm not activating it correctly? I'm pushing in both sticks at the same time but not seeing anything happen. Also, might want to change the bindings for it, as activating your scope can be disorientating during mini-games.

**Comment by sadmemesosad** [comment]
I'm having the same problem. It isn't working to operate the cheat by pressing the two buttons.
I'm a person who suffers from inconvenience in the ability to use a game controller, 
so missions like this are hard to clear. 
I feel deprived.

**Comment by bad1dea** [comment]
1) Paste the cheats you have activated (exact ones on your switch)
2) Switch or Emu?
3) What buttons are you pressing exactly?

I created the code for this purpose.. I've just retested it.. and it's working as programmed.

**Comment by 2ndHouse** [comment]
I'm using these cheats together on Yuzu:

https://t.ly/o_uOZ
https://t.ly/fBHV
https://t.ly/rHXR
https://t.ly/DYCU
https://t.ly/VnPW

I click both sticks in (L3+R3) at the same time.

**Comment by bad1dea** [comment]
Well that explains it,

The code won't work for YUZU, the emulator does not allow ASM Hacks to be in a hotkey -- from what I recall.

I'll recode the code -- should fix it.. I'll reply to this once I get around to it.. most likely later today.

**Comment by bad1dea** [comment]
```
[♯51. Add 60 Seconds To Mission Timer (L3+R3)]
080E0000 02B17ED4 17896C20 BD001D00
080E0000 02B17ECC 1E2A2800 1E2B094A
080E0000 02B17EC4 1E20100B 1E2A094A
080E0000 02B17EBC 1E27D00A 340000F5
080E0000 02B17EB4 B9401115 54000120
080E0000 02B17EAC 1E202008 54000161
080E0000 02B17EA4 710006BF 180001D5
040E0000 02B17EA0 BD401D00
040E0000 00D72F54 147693D3
040E0000 02B17EDC 00000000
80000030
040E0000 02B17EDC 00000001
20000000```

If you want you can try this code..

**Comment by bad1dea** [comment]
@sadmemesosad / @2ndHouse did this work?

**Comment by 2ndHouse** [comment]
@bad1dea Sorry I didn't get back yet. I tried the code and had my first crash of the game when accessing item menus, so I disabled it for now. It's possible it was something emulator related and not the code, but I figure I can live without that code. So, I don't actually know if the code works or not.
