### ISSUE TITLE
Do time mods work?

### ISSUE THREAD

**Issue by crluehmann** [bad1dea/NXCheats#127]
The 4 ZL(L2) time affecting mods don't seem to work.  Holding ZL and moving R3 stick doesn't seem to impact time.

Maybe I'm missing something?

**Comment by bad1dea** [comment]
Emu or switch?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Chris Luehmann ***@***.***>
Sent: Sunday, June 11, 2023 10:47:16 PM
To: bad1dea/NXCheats ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bad1dea/NXCheats] Do time mods work? (Issue #127)


The 4 ZL(L2) time affecting mods don't seem to work. Holding ZL and moving R3 stick doesn't seem to impact time.

Maybe I'm missing something?

**Comment by crluehmann** [comment]
Emu, 1.1.2, Yuzu EA.  Happy to provide any other details or I may be missing a step somewhere.  Others are working as expected.

**Comment by slacksystem** [comment]
Any word on this? I'm on switch with the most recent codes, and the time codes are not working for me either.

**Comment by crluehmann** [comment]
No update yet.  Saw another issue that lightly suggested that time based may only work on Switch hardware, so I didn't expect a further response.

**Comment by slacksystem** [comment]
Hmm well it's not working even on switch hardware for me, so I hope to see this issue updated at some point
