### ISSUE TITLE
TOTK cheats wont disable....

### ISSUE THREAD

**Issue by Miggy68** [bad1dea/NXCheats#13]
So i activated the health-stamina and durability cheats to experiment a bit and it worked flawlessly......

Only problem is after deactivating them and even removing the files from Ryujinx the stamina cheat stays in effect....

As i said it all works perfectly apart from that stamina oddity....

Any help is much appreciated as i use the cheats occasionally but not all the time....

Thanks in advance....

**Comment by digitydogs** [comment]
The current cheats cannot be disabled while the game is running. you have to exit the game, disable the cheats, then start the game up again.

**Comment by bad1dea** [comment]
That's how emulator works, you cannot disable them without restarting the emulator.
