### ISSUE TITLE
Update 1.2.0

### ISSUE THREAD

**Issue by Zatos59** [bad1dea/NXCheats#131]
Can you update cheats file for 1.2.0 ? 😊

**Comment by Simzy** [comment]
> Can you update cheats file for 1.2.0 ? 😊

Are you talking about for Tears of the Kingdom?

**Comment by Zatos59** [comment]
> > Can you update cheats file for 1.2.0 ? 😊
> 
> Are you talking about for Tears of the Kingdom?

Yes 😊

**Comment by bad1dea** [comment]
Updated.
