### ISSUE TITLE
Cheats prevent beating game. 

### ISSUE THREAD

**Issue by digitydogs** [bad1dea/NXCheats#14]
Durability causes crash between final boss defeat cutscenes.

**Comment by bad1dea** [comment]
Send a save -- you using latest durability?

**Comment by digitydogs** [comment]
Yes using latest durability.

**Comment by digitydogs** [comment]
[save.zip](https://github.com/bad1dea/NXCheats/files/11402919/save.zip)

**Comment by digitydogs** [comment]
after you defeat ganon in his final form a few cutscenes play, after the cutscene where zelda is restored the game will crash.  If you are only using health and stamina the crash doesn't happen.

**Comment by bad1dea** [comment]
Thank you will look into it now.

**Comment by bad1dea** [comment]
@digitydogs the save you sent is incorrect/does not contain save?

Are you using console? You need to use DBI/JKSV/Edizon to dump the save. should be 1.3MB

**Comment by bad1dea** [comment]
Close game -> right click -> Open user save.. should look similar to this..

![image](https://user-images.githubusercontent.com/10354814/236489754-439f3e2d-11c3-4497-b17f-432c61d5e8c2.png)

**Comment by bad1dea** [comment]
No attachment :P

**Comment by digitydogs** [comment]
[0.zip](https://github.com/bad1dea/NXCheats/files/11407603/0.zip)

Ok here it is... note to self git hates rar!

**Comment by bad1dea** [comment]
I'm fighting Demon King's Army right now.. in 3rd phase, damage goes WAYYY down (once those flyers come)

Is that normal?

**Comment by digitydogs** [comment]
I don't think i noticed.. I fudged through those battles quickly by using arrows tipped with ancient blades. Single hit takes out any enemy but ganon with one of those ;)

**Comment by bad1dea** [comment]
![image](https://user-images.githubusercontent.com/10354814/236504125-5b256d45-ca7a-4780-80cb-e0532fb276d7.png)

**Comment by bad1dea** [comment]
That's a lot of HP, that's normal?

**Comment by digitydogs** [comment]
yes that is normal! and your not done yet... next phase he eats the secret stone and transforms again.. its after beating him in the last form and plunging the master sword into him that youll encounter the crash scene... when you see link and the 2 zonai spirits cutscene the crash is at the end of that scene.

**Comment by bad1dea** [comment]
how do i hurt his dragon form? (sorry i don't play the game)

**Comment by bad1dea** [comment]
![image](https://user-images.githubusercontent.com/10354814/236506264-1589948b-df17-4969-9d4d-4a63ab9c3dc1.png)

**Comment by bad1dea** [comment]
![image](https://user-images.githubusercontent.com/10354814/236506305-fd64b266-406c-4996-acb5-d71b3f18305e.png)

**Comment by digitydogs** [comment]
sorry was on the gba forum sharing screenshots and answers to questions.

yes that is the last form. :)

**Comment by bad1dea** [comment]
![image](https://user-images.githubusercontent.com/10354814/236506734-6a906481-10a9-4b07-a330-f83c27873676.png)

**Comment by bad1dea** [comment]
![image](https://user-images.githubusercontent.com/10354814/236506991-5670f9ca-0e81-4eb7-9adb-22221a9639e4.png)

**Comment by bad1dea** [comment]
![image](https://user-images.githubusercontent.com/10354814/236507147-282a883b-a30e-4551-80f3-09c4daf9cc4c.png)

**Comment by bad1dea** [comment]
![image](https://user-images.githubusercontent.com/10354814/236507340-4370bef0-a0e9-4abb-8b30-5100cd302ec5.png)

**Comment by bad1dea** [comment]
It's fine?

![image](https://user-images.githubusercontent.com/10354814/236507473-1b4b1749-3706-469e-8542-b1861614355c.png)

**Comment by bad1dea** [comment]
It might be an Emulator thing..

![image](https://user-images.githubusercontent.com/10354814/236507588-10ec8964-9a74-4451-a5bf-fe3b1eee6cce.png)

**Comment by digitydogs** [comment]
It must be an emulator issue with ryu then. With durability on it wont let you past that screen, and ganon also will randomly get stuck between phases.  

Emulator guys will just have to deal with breaking weapons and no item multiplication for the last battle :)

**Comment by bad1dea** [comment]
> It must be an emulator issue with ryu then. With durability on it wont let you past that screen, and ganon also will randomly get stuck between phases.
> 
> Emulator guys will just have to deal with breaking weapons and no item multiplication for the last battle :)
> 
> Thanks for taking the time to look into it!

you may be using olde code....


paste the durability you using

**Comment by digitydogs** [comment]
[#03. Inf. Durability]
080E0000 02AA6FE4 177471F1 B9000901
040E0000 02AA6FE0 B9401901
040E0000 007C37A8 148B8E0E

**Comment by bad1dea** [comment]
> 

Interesting, ya that doesn't have the broken code.. so unsure. I'm confident it's an emulator thing.. :) I can try on EMU later.
