### ISSUE TITLE
TOTK update 1.2.1

### ISSUE THREAD

**Issue by Zatos59** [bad1dea/NXCheats#142]
update 1.2.1 available.
Can you update cheat file ?

**Comment by MysticalOS** [comment]
+1, your repo is normally fastest to update for new patches, but I guess you're probably on break from doing this atm, so whenever you return :D

**Comment by Arch9SK7** [comment]
Check pull requests. I posted the updated codes for TOTK 1.2.1 you should be able to see my edits in there. At least till he approves a merge to his main branch

**Comment by MysticalOS** [comment]
Oh i already grabbed them from PR moment i saw it :D

**Comment by Zatos59** [comment]
Thx for the answer, i will test this right now 😊
