### ISSUE TITLE
Request: FRONT MISSION 1st: Remake cheat codes

### ISSUE THREAD

**Issue by whitezombie2000** [bad1dea/NXCheats#145]
Hi bad1dea! Can you make cheat codes for FRONT MISSION 1st: Remake TID: 0100F200178F4000 BID: 188BF4CBE682C3AC? The latest update is 2.0.5 (v327680). Someone was making cheat codes but has stopped and is not interested in making new codes for the latest update. I am kindly requesting if some of these codes posted here can be ported to the latest update for the Switch, Ryujinx, and Yuzu. Thanks!

https://gbatemp.net/threads/front-mission-1st-remake-1-0-3-tid-0100f200178f4000-bid-f704ded60006ecba.624394/page-3#post-10250865

https://gbatemp.net/threads/front-mission-1st-remake-1-0-3-tid-0100f200178f4000-bid-f704ded60006ecba.624394/post-10065860

**Comment by whitezombie2000** [comment]
I assume this means you are not going to update them? :(

**Comment by bad1dea** [comment]
I asked GamerJin (the creator) to look at it .... I don't have the game, and I forget there was a reason I didn't do the game.. which I can't remember off hand.

You just want the codes he made for the latest?

**Comment by whitezombie2000** [comment]
Yeah the codes GamerJin made for the latest update would be nice.  GamerJin stated he won't update them anymore in the GBA thread for the latest update.

**Comment by bad1dea** [comment]
i'm trying to convince him :D if he doesn't i'll port his codes over.

**Comment by whitezombie2000** [comment]
Also if you could when you have the time, can you kindly update Crisis Core to v1.0.4?
