### ISSUE TITLE
[Hogwarts Legacy] cheat codes crashed update 1.0.2

### ISSUE THREAD

**Issue by zhengyilab** [bad1dea/NXCheats#147]
Thanks for the great work on this, it runs perfect on version 1.0.1.

However, multiple cheat codes crashed after updated to 1.0.2, including infinite health, damage multiplexer, slower AI (will hit the player too)... It crashes when the player making any spells or attacks enemies, with any codes enabled except for the 'restore codes'. 
Similar ideas also reported on the original thread here:
https://gbatemp.net/threads/hogwarts-legacy-tid-0100f7e00c70e000.642904/page-6  

Hope if there'll be any updates on the code fix. Thx!

**Comment by bad1dea** [comment]
fixed... in latest commit

**Comment by bad1dea** [comment]
https://github.com/bad1dea/NXCheats/commit/6f6883ca6508df44ac950b5d1d2e78c6c22c6f0c
