### ISSUE TITLE
Link for Super Mario RPG item drop spreadsheet broken

### ISSUE THREAD

**Issue by D1g1Byt3** [bad1dea/NXCheats#148]
The link provided under for Item Drop is broken. It says page does not exist.
![2023-12-27 11_14_31-Page Not Found — Mozilla Firefox](https://github.com/bad1dea/NXCheats/assets/800872/d3f26b94-ca04-481b-938e-73c892fe85b0)

**Comment by bad1dea** [comment]
https://docs.google.com/spreadsheets/d/e/2PACX-1vRbw5pNbLt_aTgJGIZ8Ti1TAnw8aBIa1teZPr8sSyfu_oLQcvluR8R28Cko8R0pcvkMEZWzY-BHpQQV/pubhtml

works fine?
