### ISSUE TITLE
TotK Durability 

### ISSUE THREAD

**Issue by F-Lambda** [bad1dea/NXCheats#17]
Would it be possible to create a 10x durability variant? Thanks anyways, even if it's not possible

**Comment by bad1dea** [comment]
Right now the Inf. Durability sets current to max of item..

I assume you're asking to make everything 10x but still breakable?

**Comment by ZeroCool940711** [comment]
@bad1dea any chance you can make a cheat for infinite durability on Zonai devices such as the wings, platforms, fans, etc?
it seems like building vehicles is limited because those things just break after like a minute or so of flying which is a shame, specially for moving easily around the sky islands.

**Comment by bad1dea** [comment]
> 

I'm unsure what you're asking -- do these devices break.. (I do not play the game) I made the Inf. Battery, since someone said it runs out unless you recharge it, or give it some time.

**Comment by digitydogs** [comment]
This would be a huge benefit to have. The use of building in game is drastically reduced by the seemingly random durability of zonai devices.  

My save is sent you should have plenty of the zonai devices for you to work with to locate the memory addresses.  999 of almost every type ;)

**Comment by Franseven** [comment]
bow did break even with the equipment durability do not decrease cheat, i'm on 1.01

**Comment by bad1dea** [comment]
> 


From fire?

**Comment by Franseven** [comment]
i don't think it was fire, but i wasn't paying particular attention

**Comment by Franseven** [comment]
yep i confirm, durability cheat doesn't work properly

**Comment by Franseven** [comment]
even normal weapons break, i use master code invicibility on, inf stamina inf arrows inf batteries  and equip durability, telling this for possible conflicts

**Comment by bad1dea** [comment]
> 

I have no Master Code, so I'm not sure you're using my code.. I've tested durability, and nothing has ever broken for me.

If something is breaking, send me a save and tell me which weapon.. + what codes you are using..

**Comment by Franseven** [comment]
my bad it works

**Comment by bad1dea** [comment]
> 

:)

**Comment by Franseven** [comment]
sorry for the ot, i'm not sure if it's related to your cheats but i have 8 batteries unlocked, when i enable inf battery cheat, i see only 2 batteries during the loading screen, even tho it still counts 8 in actual utilization, could you confirm this behavior? i hope its not permanent on the save file

**Comment by bad1dea** [comment]
> 

its not perm, but can you send me your save.

**Comment by Franseven** [comment]
https://drive.google.com/file/d/1caEl5Z9aVSmwhtNdaUSanlpNLta2R_E3/view?usp=share_link

**Comment by Franseven** [comment]
do you like my save? :D

**Comment by bad1dea** [comment]
![image](https://user-images.githubusercontent.com/10354814/236589339-71b46dca-1b29-42e6-abf2-6c451e0ed1d7.png)

**Comment by bad1dea** [comment]
You talking about that loading screen?

**Comment by Franseven** [comment]
yes

**Comment by bad1dea** [comment]
So what's the problem? It clearly shows 7 batteries there?

**Comment by Franseven** [comment]
so without the cheat it brings back the correct number, nice sorry

**Comment by bad1dea** [comment]
What cheats do you have enabled? (copy and paste them here)
Are you on console or emulator?

**Comment by bad1dea** [comment]
My Inf Battery copies whatever you have max to current, so unless there's something wrong with the cheat? I'm unsure.

**Comment by bad1dea** [comment]
The picture is with the cheats on.

**Comment by Franseven** [comment]
[#01. Inf. Health]
080E0000 02B1FFF8 176E2C34 F9400008
080E0000 02B1FFF0 B9000808 34000048
040E0000 02B1FFEC B9401808
040E0000 006AB0C8 1491D3C9
040E0000 009E9BFC D503201F

[#02. Inf. Stamina]
040E0000 007FBA10 BD405E61
080E0000 00D0B8C4 F290000F D2A8B76F
040E0000 00D0B8CC B900026F

[#03. Inf. Durability]
080E0000 02B1FFE4 177BBA96 B9000901
040E0000 02B1FFE0 B9401901
040E0000 00A0EA3C 14844569

[#04. Inf. Battery]
040E0000 00B97364 BD004669
040E0000 00B973DC BD004669


both switch and now i'm continuing on yuzu

**Comment by bad1dea** [comment]
v1? or 1.1?

**Comment by Franseven** [comment]
1.1

**Comment by bad1dea** [comment]
I see the problem, wonder why it's happening. :)

**Comment by Franseven** [comment]
me too :D
