### ISSUE TITLE
TOTK Inf. Item Usage (Eat)

### ISSUE THREAD

**Issue by Mikadocrea** [bad1dea/NXCheats#18]
with the cheat Inf. When you eat cooked food, it disappears and doesn't stay in your inventory because it only has one unit, but cooked food isn't stackable so you can't have more than one.
Is it possible to do a cheat that makes the use of cooked food infinite?
And is it possible to make a cheat that does not require the item to upgrade armour or horse (with Horse Fairy) with the Great Fairy?

**Comment by bad1dea** [comment]
The Inf Items (eat) cheat is only for eating from materials, not food.. I'll add food later, there's other codes for it already, so I'm not replicating them till later.
