### ISSUE TITLE
infinite durability crashing when disabled

### ISSUE THREAD

**Issue by antabaka-yes** [bad1dea/NXCheats#19]
tried disabling cheats on ryujinx, but inf durability is resulting in crashes when cheat is disabled.

read that this one needs to be disabled for the goron temple boss fight, which i am close to

**Comment by bad1dea** [comment]
This only happens on Emulator(s), does not happen on switch console.

I tested today on Final Bosses + A few Temple Bosses -- worked fine/as intended.

**Comment by antabaka-yes** [comment]
should probably put that in your read me lmao

**Comment by bad1dea** [comment]
> should probably put that in your read me lmao

Emulator problems are emulator problems, I can't fix it -- if it works on Emu's then I'm glad -- but my stuff is for consoles.

"Repository for cheats I've made or worked on for the switch."
