### ISSUE TITLE
not working on ryujinx

### ISSUE THREAD

**Issue by Sultansmooth** [bad1dea/NXCheats#20]
none of the cheats take any effect, on version 1.1.761 of ryujinx and version 1.0 of game.

**Comment by digitydogs** [comment]
Downgrade your ryu version for now and file a bug with them. they have been randomly breaking cheats between updates then fixing them a version or two later.

**Comment by Sultansmooth** [comment]
what version is working?

**Comment by aucklander** [comment]
i tried ryujinx-1.1.760,1.1.741,1.1.748 then gave up

**Comment by bad1dea** [comment]
I removed v1.0 cheats -- as I've migrated to 1.1.0 -- all the cheats that I made originally work(ed) for Ryu, as I tested it myself.

They all work currently for latest.. if it isn't you're doing something wrong. Post a screenshot.

**Comment by jzzunl** [comment]
ive placed the txt in Ryujinx/mods/contents/0100F2C0115B6000/ like the ryujinx wiki says to and they arent working

**Comment by Remeck24** [comment]
> I removed v1.0 cheats -- as I've migrated to 1.1.0 -- all the cheats that I made originally work(ed) for Ryu, as I tested it myself.
> 
> They all work currently for latest.. if it isn't you're doing something wrong. Post a screenshot.


I did follow the steps and tried the cheats of version 1.0, but I followed the same steps but some tricks do not work for me, such as stamina, health, inf battery, arrow, etc. dont work for me

I have it just like I did the first time, now with version 1.1 I did the same, but some of them don't work as I said

![Sin título](https://user-images.githubusercontent.com/132738276/236607901-16fa1ffe-d752-45ad-afb8-4dbe6d640f72.png)

**Comment by bad1dea** [comment]
![image](https://user-images.githubusercontent.com/10354814/236629698-ff79783b-18e2-4ebe-a1c9-f51b7a9d2c3a.png)
![image](https://user-images.githubusercontent.com/10354814/236629745-d071d8c7-a29c-4872-8372-4208bc354ff7.png)
![image](https://user-images.githubusercontent.com/10354814/236629756-75a8b42e-d46c-47bd-b866-604171049d80.png)
![image](https://user-images.githubusercontent.com/10354814/236629787-d4ca85df-b60a-43a9-8260-c88c15ac111c.png)

**Comment by bad1dea** [comment]
Can confirm, it is working with latest Ryu as of right now..

**Comment by HyrulePie** [comment]
Same. The only one thats worked for me is content of 082CE09B06E33A12 haha the one with like 7 cheats, these updated ones dont work

**Comment by bezfreely23** [comment]
> ![image](https://user-images.githubusercontent.com/10354814/236629698-ff79783b-18e2-4ebe-a1c9-f51b7a9d2c3a.png) ![image](https://user-images.githubusercontent.com/10354814/236629745-d071d8c7-a29c-4872-8372-4208bc354ff7.png) ![image](https://user-images.githubusercontent.com/10354814/236629756-75a8b42e-d46c-47bd-b866-604171049d80.png) ![image](https://user-images.githubusercontent.com/10354814/236629787-d4ca85df-b60a-43a9-8260-c88c15ac111c.png)

It LOOKS as if it wors, but it doesnt.. it lets me enable them, as well, but they DO NOT WORK in the game....

**Comment by bezfreely23** [comment]
It lets me enable them.. It shows me that they've been correctly dumped into the game files, but they simple dont work, in game.. I have the latest Ryujinx update.. Ive also tried another persons cheats, for this game and got the same exact result.. you can see them there, but they dont work..

**Comment by bad1dea** [comment]
Works fine, you're using a different version.
