### ISSUE TITLE
Which version do you need to use for this? 1.0.0 or 1.1.0?

### ISSUE THREAD

**Issue by Evn99** [bad1dea/NXCheats#24]
Basically title

**Comment by Evn99** [comment]
for the zelda one*

**Comment by bad1dea** [comment]
1.1.0

**Comment by littleneutrino** [comment]
> 1.1.0

I haved tried it on both 1.1.0 and 1.0.0 and they work on 1.0.0 but not 1.1.0 (Specifically on Ryujinx 1.1.760)

**Comment by Milicksp** [comment]
someone was able to get it working on 1.1.0? in the previous version if it worked

**Comment by bad1dea** [comment]
I've tested it, and others have reported it working... It's most likely a user error. Please read Emu FAQ's from the emu makers on how to install properly.
