### ISSUE TITLE
totk: Hinding buttons HUD elements

### ISSUE THREAD

**Issue by Anatharias** [bad1dea/NXCheats#25]
It would be super awesome if a cheat would allow for selective removal (hiding) of the AB XY UI elements. as swapping the buttons for western like button mapping just tricks the brain badly since the game displays the Nintendo button location mapping, while the buttons are like Xbox mapping.
If the button to push was displayed, this would be fine, but each time you see it located on a cross like pattern with A being on the right, while western A is at the bottom of the controllers buttons.
Thanks

**Comment by bad1dea** [comment]
There's an option to hide hud, but I don't do GFX mods.
