### ISSUE TITLE
Not working on Ryujinx 1.1.763 and 1.0

### ISSUE THREAD

**Issue by fernandoesra** [bad1dea/NXCheats#27]
None of the cheats take any effect, on version 1.1.763 of ryujinx and version 1.0 of the game.

The log errors:

![](https://i.imgur.com/suskzFU.png)
https://i.imgur.com/suskzFU.png

Thanks for the work.

**Comment by Evoley** [comment]
That's because you're most likely using the newer cheats for 1.1.

**Comment by bad1dea** [comment]
The error message is quite clear, you are not using the correct version.

**Comment by fernandoesra** [comment]
Thank you very much for your answers. I didn't know there were different versions of the cheats, I'm not able to see where it mentions which version of the game the cheat file is for. I will try to update the copy of the game Thanks for the work!
