### ISSUE TITLE
Item pick up multiplier make blueprint broken

### ISSUE THREAD

**Issue by yun-wulian** [bad1dea/NXCheats#28]
when turn it on then blueprint cant save and load machines.

**Comment by throwingbanana** [comment]
Can confirm this. Even after disabling the cheat and using the „reset“ code, the issue persists. Save is f‘ed now.

**Comment by throwingbanana** [comment]
Update: Loaded an older save I had backed up. Tried it again and it didn't f up immediately. Could it be linked to picking up/getting new blueprints while having it activated? I noticed that my history was up to 60-70 when it was corrupted, as opposed to the regular 30 you have. Might be worth to add a warning. Will update if it corrupts again, but for now I leave it disabled.

**Comment by epl609** [comment]
At what point(s) do you come into the blueprints first for us to keep an eye out?

**Comment by throwingbanana** [comment]
Underground. Whenever you are at a Yiga spot or in a Abandoned Mine.

**Comment by bad1dea** [comment]
Please send save file and description of how to duplicate error/bug.

**Comment by MW1Z4RD** [comment]
I use the Yuzu emulator, and I have encountered the same issue. I changed the picking multiplier to 50, and when I use the blueprint, it generates a history record and 50 blank slots. However, when I disable the cheat, remove all favorites in the blueprints, and rebuild a device, the blueprint returns to normal.

**Comment by wswslzp** [comment]
Guys, currently I didn't go underground and get blueprint yet but have used this cheat (item multipier) before, will this cheat break down my save?

Also is there a workaround to use item multiplier cheat and blueprint without this problem? I see that item multiplier cheats are removed in the latest commit.

**Comment by youngbab** [comment]
Is there a way to fix the save file? I have the blank space in favourites too, next to another build that I cannot remove from favourites. - Also, thanks for the cheats they work amazing other than this little issue!

**Comment by epl609** [comment]
Only thing I know you can do is roll back a few saves and turn the cheat off. I always ensure the cheat is off while using ultrahand. Hopefully this is helpful. Cheers.

**Comment by bad1dea** [comment]
I'm unsure what you guys are talking about -- could you take screenshots?

**Comment by bad1dea** [comment]
No one's sent me any save file for this issue, with description/comments about how to replicate/show issue.

**Comment by youngbab** [comment]
> Only thing I know you can do is roll back a few saves and turn the cheat off. I always ensure the cheat is off while using ultrahand. Hopefully this is helpful. Cheers.

Ah shame, it was a while ago before I noticed it. Don't have a save before then - thanks anwyays!


![image](https://github.com/bad1dea/NXCheats/assets/40214450/34fa8b57-0205-486f-aa61-3b9183983454)


> I'm unsure what you guys are talking about -- could you take screenshots?
Here you go man, just a screenshot though - can I just upload my save here?
![image](https://github.com/bad1dea/NXCheats/assets/40214450/34fa8b57-0205-486f-aa61-3b9183983454)

**Comment by MW1Z4RD** [comment]
> I'm unsure what you guys are talking about -- could you take screenshots?

@bad1dea 
This is my saved file after picking up items 50 times. It was created using the Yuzu emulator. Please try using this saved file. Whether cheats are enabled or not, when loading this saved file, the blueprint will show 50 blank space. Disable cheating, then clear the favorites, and then recreate any object. The blueprint will be restored.

[0000000000000000.zip](https://github.com/bad1dea/NXCheats/files/11488888/0000000000000000.zip)

These are some screenshots.
![1](https://github.com/bad1dea/NXCheats/assets/104913036/1ebce88e-093d-4a76-9a7f-07a3c3b34786)
![2](https://github.com/bad1dea/NXCheats/assets/104913036/54b6b2cd-0094-4ae3-bed7-cd85aa809c82)
![3](https://github.com/bad1dea/NXCheats/assets/104913036/a724d6f9-788a-485f-b014-f556d1b1d012)

> Guys, currently I didn't go underground and get blueprint yet but have used this cheat (item multipier) before, will this cheat break down my save?
> 
> Also is there a workaround to use item multiplier cheat and blueprint without this problem? I see that item multiplier cheats are removed in the latest commit.

@wswslzp If you follow what I'm saying and cancel cheating, clear favorites, remake an object, the blueprint  will return to normal, and your save file will not be corrupted.

**Comment by youngbab** [comment]
> @wswslzp If you follow what I'm saying and cancel cheating, clear favorites, remake an object, the blueprint will return to normal, and your save file will not be corrupted.

Does removing the favourites work for you then? When I try it just does nothing

**Comment by youngbab** [comment]
> Thanks -- where do you pick up the.. blueprints?
> 
> (I don't play this game -- so it's hard for me to find things on my own)

Ah right - well they are collectibles that different NPCs give around the map, they aren't in just one place.
Also, it's amazing you were able to do all this without even playing the game - thanks again!

**Comment by bad1dea** [comment]
I changed the code, should work.. let me know.. (you must grab latest codes.. not pick and choose, as a lot of the code cave addresses are reused/redone)

**Comment by MW1Z4RD** [comment]
> > @wswslzp If you follow what I'm saying and cancel cheating, clear favorites, remake an object, the blueprint will return to normal, and your save file will not be corrupted.
> 
> Does removing the favourites work for you then? When I try it just does nothing

Yes, disable cheating, remove all favourites , especially from historys, and then rebuild an object，and the blank spaces in the blueprint will disappear. This is work for me.
