### ISSUE TITLE
Perfect Goldilocks Thermometer doesn't work against unbearable heat

### ISSUE THREAD

**Issue by Xiphus** [bad1dea/NXCheats#29]
I'm running the cheat on Edizon for Switch, but it seemingly only works against cold, in the desert area it doesn't do anything against the heat.

**Comment by bad1dea** [comment]
Like you still burn?

**Comment by bad1dea** [comment]
I checked, it looks like super fire doesn't get protected

**Comment by Xiphus** [comment]
Yeah you still take damage from the heat.

**Comment by bad1dea** [comment]
Please send save file and description of how to duplicate error/bug.

**Comment by bad1dea** [comment]
Fixed.
