### ISSUE TITLE
[Inf Durability] Fused weapons will still break with infinite durability cheat.

### ISSUE THREAD

**Issue by ryanzhang95** [bad1dea/NXCheats#31]
During my playthrough of totk I had the infinite durability cheat turned on.  I confirmed it was working with a few tree branches in the tutorial.  However, I noticed that my fused weapon of two bokoblin arms still broke when hitting wooden boxes.  Not sure if this is an issue specific to two base weapons fused together, or if it still happens with a weapon + item fusion.  Thank you all for your work so far!

**Comment by ryanzhang95** [comment]
Wanted to confirm - this isn't just with wooden boxes/panels, it seems like weapons fused with weapons will eventually break, even with the cheat turned on

**Comment by bad1dea** [comment]
Please send save file and description of how to duplicate error/bug.

**Comment by F-Lambda** [comment]
It also appears to occur when fusing a zonai device to a sword, though I'm unsure of the speed at which it damages the item.

1. Equip a brand new weapon, such as an Soldier's Broadsord (flash in top right indicating unused).
2. Drop a zonai device, such as a flame emitter.
3. Fuse the zonai device onto the weapon.
4. Swing the weapon a few times. Upon checking the menu, you will see that the flashing sparkle indicating a brand new weapon has disappeared.

This only appears to affect weapons; shields with zonai devices attached appear to remain brand new.

[slot_01.zip](https://github.com/bad1dea/NXCheats/files/11468030/slot_01.zip)

**Comment by bad1dea** [comment]
Can you test this..

```
[#01. test durability]
080E0000 02B1FFF8 D65F03C0 B9000901
040E0000 02B1FFF4 B9401901
040E0000 006920EC 948444A4
040E0000 006920EC 9484456E```

**Comment by bad1dea** [comment]
@F-Lambda / @Alceris 

```
[#06. Inf. Equipment Durability (Fire will still break it.)]
040E0000 01B832FC 1B09A3E8
080E0000 02B1FFB4 D65F03C0 B9000901
040E0000 02B1FFB0 B9401901
040E0000 00A0ED64 94844493
040E0000 00A0EA3C 9484455D
```
