### ISSUE TITLE
[Inf. Health] Enabling will prevent Link from grabbing on to time-reversable enemy objects

### ISSUE THREAD

**Issue by Marybytes** [bad1dea/NXCheats#33]
When the infinite health is enabled, Link will always get knocked back when attempting to touch / climb enemy projectiles that are meant to be time-reversible.

Example when fighting a flux construct:
When the enemy transforms into a platform, it will fly up high and start launching blocks at Link.

The expected solution would be to jump on the block, reverse time, and be able to land on the enemy to continue the fight

What happens instead is that attempting to jump on the block will knock Link back.  This makes fights with any enemy that makes use of this mechanic impossible to beat

**Comment by bad1dea** [comment]
Please send save file and description of how to duplicate error/bug.

**Comment by Marybytes** [comment]
Here is my save file extracted using Edizon: https://drive.google.com/file/d/1Z1JTSMOeF_EZXHkA4Ss-9_UarBcXCNy7/view?usp=share_link

The main save should have Link right on the edge of a Flux Construct III boss fight.

Steps to reproduce:
1. Enable infinite health
2. Proceed to fight the boss until it turns into a floating platform
3. Boss will start launching blocks at Link
4. Get hit by blocks
5. Getting hit will cause Link to lose all hearts [all hearts will then be regained due to infinite health]
6. Wait for the boss to launch another group of blocks at Link
7. Dodge the blocks -> blocks should not be moving at this point
8. Attempt to jump on the block, Link should then get knocked back

Please let me know if I can provide more details

**Comment by bad1dea** [comment]
If you don't have the cheat on @Marybytes you should be able to jump on the blocks?

**Comment by KarmaAlex** [comment]
Also literally just ran into another minor issue lol, may or may not be related to the same thing you're fixing right now but getting eaten by a like like causes you to get stuck inside it which results in a softlock
https://drive.google.com/file/d/1W1z7A5bApvjlHPrrGgZqg4zmLd3PxBw_/view?usp=sharing
Save right next to one
Thanks in advance for the fixes

**Comment by bad1dea** [comment]
> Also literally just ran into another minor issue lol, may or may not be related to the same thing you're fixing right now but getting eaten by a like like causes you to get stuck inside it which results in a softlock https://drive.google.com/file/d/1W1z7A5bApvjlHPrrGgZqg4zmLd3PxBw_/view?usp=sharing Save right next to one Thanks in advance for the fixes

![image](https://github.com/bad1dea/NXCheats/assets/10354814/5213c80f-d061-4775-8dde-d69fe1e373d6)


this thing suppose to eat me?

**Comment by KarmaAlex** [comment]
Yeah it happened to me in that cave, i think if you're close enough it won't shoot lightning balls but will try to eat you instead. If you can't get it to eat you there is a like like next to tadarok shrine on the great plateau
![image](https://github.com/bad1dea/NXCheats/assets/48263019/5a5a48de-fd27-4b5e-89d0-0bb498bc20ee)

**Comment by bad1dea** [comment]
Dumb q, sorry I don't really play the game, is there a way to tell your companions to stop doing shit like hitting it?

**Comment by KarmaAlex** [comment]
you can disable them from the key items menu, use the vow of yunobo and vow of tulin items and select dismiss

**Comment by bad1dea** [comment]
Should be fixed now, could you test -- the eating.. and the other weird things you couldn't climb on?

**Comment by KarmaAlex** [comment]
seems like everything works now, thank you very much

**Comment by bad1dea** [comment]
> 

Does this fix the OP's issue too?

**Comment by KarmaAlex** [comment]
yes i was able to climb onto the flux construct to damage it

**Comment by bad1dea** [comment]
Seems like it's fixed.. :) I'll reopen if someone else encounters an issue.

**Comment by DarioMelo** [comment]
With the new code the game freezes at startup for me on Yuzu (loads the game but it's stuck in a black screen). I narrowed it down to this cheat. Old code still works, except for the issue mentioned by OP.

**Comment by bad1dea** [comment]
> With the new code the game freezes at startup for me on Yuzu (loads the game but it's stuck in a black screen). I narrowed it down to this cheat. Old code still works, except for the issue mentioned by OP.

I just tested, and it loads fine -- Are you using the Brand new Zip -- or just replaced the one cheat? If you replaced just one cheat it'll not work.

**Comment by DarioMelo** [comment]
Alright my bad, I was using the new codes together with an old one, but this one is the only that had a conflict with it. It was the item multiplier btw, why was that removed?

**Comment by bad1dea** [comment]
I changed the way the multiplier was done.. because others complained about blueprint issues with it.

Retest with latest, and let me know if its still an issue, I'll reopen

**Comment by DarioMelo** [comment]
Sorry didn't realize they were updated too, last I checked they were gone. Works great, thanks!

**Comment by Werner1201** [comment]
Is it updated on EdiZon? I applied the cheat 15th of may
