### ISSUE TITLE
Item Multiplier

### ISSUE THREAD

**Issue by Moglibogli** [bad1dea/NXCheats#34]
Are the Item multipliers for totk gonna apply to animals and mob drops eventually? or certain other items. it applies to some things and not others and I'm wondering if it's intentional or not.

**Comment by Moglibogli** [comment]
Turns out you need at least 2 items to start duplicating. You need to have something in your inventory to duplicate.

**Comment by bad1dea** [comment]
You need at minimum of 1 already in inventory (so 2)
