### ISSUE TITLE
Zelda TOTK not working in Yuzu

### ISSUE THREAD

**Issue by polwex** [bad1dea/NXCheats#37]
The Ryujinx version did work for me. Does anyone have it working on Yuzu?

**Comment by Moglibogli** [comment]
What do you mean by this

**Comment by polwex** [comment]
I mean that I loaded [these files](https://github.com/bad1dea/NXCheats/blob/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom/0100F2C0115B6000%20for%20Yuzu.7z) on the Yuzu emulator but the cheats do not work. I get damage, stamina drains as normal, etc.
The cheats did work on Ryujinx.

**Comment by bad1dea** [comment]
Emu/User Issue, please read wiki on how to use yuzu cheats.
