### ISSUE TITLE
Cheats not Functioning TOTK 1.1.0 latest ryujinx (1.1.786 or 1.1.743)

### ISSUE THREAD

**Issue by ThunderousLeft** [bad1dea/NXCheats#38]
see error messages, cant seem to make use of selling cheats at any multiplier, has trouble loading

![image](https://github.com/bad1dea/NXCheats/assets/16866924/800791bc-70ac-4e17-a99b-aef10ecb3ba0)

**Comment by bad1dea** [comment]
Paste the cheat(s) / cheat file you are using.
