### ISSUE TITLE
FPS Hack does not work - Zelda Tears of the Kingdom

### ISSUE THREAD

**Issue by linkinstreetGit** [bad1dea/NXCheats#41]
Cheat used - [0100F2C0115B6000 for Ryujinx](https://github.com/bad1dea/NXCheats/tree/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom/0100F2C0115B6000%20for%20Ryujinx)

Issue - #16. 60 FPS Does not work

What did I expect - 60FPS

What happened - Nothing. Game still stuck at 20FPS

Any other info - If you use the 60/30FPS exefs hack, then framerate would work as expected, but some of the cheats won't work. Only [#15. (X) Jump] would work.

**Comment by AlexanderNLD** [comment]
Hi, sorry for off topic, how do i use that cheat? i get just a txt file, what do i do with that?
