### ISSUE TITLE
Missing Item Mulltiplier

### ISSUE THREAD

**Issue by N0X-44** [bad1dea/NXCheats#43]
Accidentally deleted old zip, can't paste into new update.

**Comment by Tigerkushhh** [comment]
[#11a Item Pickup/Sell/Buy Multiplier (2x)]
040E0000 02B1FFD8 00000002
080E0000 02B1FFD0 17E3F1DD 0B01014A
080E0000 02B1FFC8 1B057C21 34000045
080E0000 02B1FFC0 5400006D 3100043F
080E0000 02B1FFB8 180000E5 540000ED
080E0000 02B1FFB0 3100043F 34000065
040E0000 02B1FFAC 18000185
040E0000 0241C744 141C0E1A

[#11b Item Pickup/Sell/Buy Multiplier (5x)★]
040E0000 02B1FFD8 00000005
080E0000 02B1FFD0 17E3F1DD 0B01014A
080E0000 02B1FFC8 1B057C21 34000045
080E0000 02B1FFC0 5400006D 3100043F
080E0000 02B1FFB8 180000E5 540000ED
080E0000 02B1FFB0 3100043F 34000065
040E0000 02B1FFAC 18000185
040E0000 0241C744 141C0E1A

[#11c Item Pickup/Sell/Buy Multiplier (10x)]
040E0000 02B1FFD8 0000000A
080E0000 02B1FFD0 17E3F1DD 0B01014A
080E0000 02B1FFC8 1B057C21 34000045
080E0000 02B1FFC0 5400006D 3100043F
080E0000 02B1FFB8 180000E5 540000ED
080E0000 02B1FFB0 3100043F 34000065
040E0000 02B1FFAC 18000185
040E0000 0241C744 141C0E1A
