### ISSUE TITLE
Is there any chance to add a freeze timer? (Zelda Tears of the Kingdom, Yuzu)

### ISSUE THREAD

**Issue by MegaMimh** [bad1dea/NXCheats#47]
Hi, 
I hope I posted in the right place, otherwise I apologize.
Thank you for all these codes, but is there any chance to have one that allows to freeze the time count please? 
I use special gamepad because of my handicap and when there are limited time events it is very complicated for me.
 Thanks a lot :)

**Comment by bad1dea** [comment]
Send me a save where there is a timer?

**Comment by MegaMimh** [comment]
Here is a save with a limited time quest. 
The save is right in front of the pnj. 
I'm new to this game, but I know that in the old Zelda the time limit events are quite recurrent, I just suppose that this one is the same and must surely propose others.
https://1drv.ms/u/s!AsZgZR_sCQo_gQUaeDIZUupyg_Rp?e=t98lZR
Thx

**Comment by bad1dea** [comment]
I haven't been able to find the timer.. for some reason

**Comment by MegaMimh** [comment]
I've moved on in the game and haven't seen any more yet. 
Thanks for trying :)

**Comment by bad1dea** [comment]
Hah, you can.. actually freeze the timer now I think -- I added a time/day stopper..

I also asked GamerJin for help and he found the timer, so I can create code now.

**Comment by bad1dea** [comment]
Okay Good news!

![image](https://github.com/bad1dea/NXCheats/assets/10354814/99a66bec-ef38-413c-95f7-5ee9f4e3fa7f)

**Comment by MegaMimh** [comment]
Ah great, thank you very much, I'll look into it right away :)
