### ISSUE TITLE
TOTK cheats clashing with gbatemp fps patches

### ISSUE THREAD

**Issue by fredso104** [bad1dea/NXCheats#50]
I was having issues with the fps patches on gbatemp, the animations were still sped up when over 20fps, but these issues were fixed every time I removed the cheats. Is it possible to fix this? Or is it a specific cheat that I shouldn't enable? I'm not sure how exactly your cheats would interfere with animation speed, I don't have any speed cheats enabled.

**Comment by fredso104** [comment]
Your new update fixed this, thanks!

**Comment by fredso104** [comment]
Sorry, I was mistaken and closed the issue. This is still a problem

**Comment by bad1dea** [comment]
What patches from gba?

**Comment by fredso104** [comment]
These ones here https://gbatemp.net/download/loz-tears-of-the-kingdom-fps-static-fps-and-visual-fixes-patch-collection.37996/history

**Comment by fredso104** [comment]
I have absolutely no idea why, but this is fixed for me now. Thank you for your time.
