### ISSUE TITLE
can't cut down tree's

### ISSUE THREAD

**Issue by thumperskunk** [bad1dea/NXCheats#51]
Cheat used - [The Legend of Zelda Tears of the Kingdom/0100F2C0115B6000 for Ryujinx/The Legend of Zelda Tears of the Kingdom (US) v196608/cheats](https://github.com/bad1dea/NXCheats/blob/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom/0100F2C0115B6000%20for%20Ryujinx/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom%20(US)%20v196608/cheats/168DD518D925C7A3.txt)

Issue - can't cut down tree's when cheat # 10 infinite zonai device duration (no blink + Despawn) enabled

What did I expect - to cut down trees

What happened - Nothing. can't cut down tree's, devices do not despawn though which is nice

Any other info -  attached screenshot and save as proof, don't know if the save is helpful
![treeeee](https://github.com/bad1dea/NXCheats/assets/72983630/226be4ad-d374-4eab-915b-6bb84d6409a7)
[slot_02.zip](https://github.com/bad1dea/NXCheats/files/11520679/slot_02.zip)

**Comment by bad1dea** [comment]
LOL

Thanks I'll take a look.

**Comment by bad1dea** [comment]
![image](https://github.com/bad1dea/NXCheats/assets/10354814/b6cd1f8a-3718-4f7c-aead-50076cf3e554)

**Comment by thumperskunk** [comment]
I take it, you couldn't reproduce my issue?

**Comment by bad1dea** [comment]
Nope, and no one else I was talking too could either?

**Comment by thumperskunk** [comment]
sending my files to a friend, having them test and see if i can't figure it out, could be my nsp or install i suppose

**Comment by bad1dea** [comment]
Might be emu related, but I'm checking

**Comment by Chronoxshift** [comment]
Works for me with their Save File. Having skunk reinstall game, and will test again.

**Comment by Niflis** [comment]
Got the same issue!! Can't cut down trees with the "infinite zonai device duration (no blink + Despawn)" enabled

tried on 1.1.0 and 1.1.1 aswell

**Comment by thumperskunk** [comment]
i can now suddenly chop down tree's, i changed nothing, could be an area issue with the tutorial island?

**Comment by Niflis** [comment]
I'll try some more, but i had the issue everywhere. 
Will follow up again

**Comment by Niflis** [comment]
Nah, still the same here.. 

![Screenshot_1](https://github.com/bad1dea/NXCheats/assets/25751619/4d24535b-5690-4221-a326-9707f0859fdb)

**Comment by Niflis** [comment]
@thumperskunk you changed nothing? 
No updates or anything like that? and same mods are still active as before?

**Comment by thumperskunk** [comment]
I just kept playing the game and every time I needed a chop down a tree I used a bomb. I was in mid combat and there was an enemy. I attacked him hit the tree on accident and chopped it down so i was like wait what

**Comment by bad1dea** [comment]
Fixed.
