### ISSUE TITLE
Does this code works for middle east/southeast asia version ?

### ISSUE THREAD

**Issue by KOSlance** [bad1dea/NXCheats#52]
I own totk middle east/southeast asia version. Will the cheats works
![Screenshot_20230520_084633_Carousell](https://github.com/bad1dea/NXCheats/assets/130059940/b031c052-6f33-40e8-9c79-fcd9420e7ac4)

**Comment by bad1dea** [comment]
It should, if it doesn't send me your main exefs from the most updated patch.
