### ISSUE TITLE
Possibility of cheat for timescale/day length?

### ISSUE THREAD

**Issue by declandaman** [bad1dea/NXCheats#53]
Hey, love your stuff. Wondering how possible it is to make cheats for the day duration? I think default is way too quick. I've had a look through the dump files to see if it was moddable but no luck. Any insights?

**Comment by declandaman** [comment]
Bumping this, any ideas?

**Comment by GLiTcH2** [comment]
This mod gives longer day/night cycles, Default time is 24 minutes and you can download 36, 48, 60 or 120 minutes however the only problem currently is it's only working for version 1.1.0 of the game. Mod link here: https://gamebanana.com/mods/446105 also in the comments there are mixed results with it working...

**Comment by bad1dea** [comment]
I can.. stop time/make time faster/rewind time

Is that what you want?

**Comment by bad1dea** [comment]
I added codes for the latest 1.1.2 - I pushed it, if you want to test.

[code]
[#43. 2x Longer Days]
040E0000 00AE3144 1E2E1008

[#44. 3x Longer Days]
040E0000 00AE3144 1E2C1008

[#45. 4x Longer Days]
040E0000 00AE3144 1E2A1008

[#46. Time - ZL+RS↓ or RS↑ Stop or Resume - ZL+RS← or RS→ RW or FF]
80800100
040E0000 00AE3150 D503201F
20000000
80200100
040E0000 00AE3150 1E212901
20000000
040E0000 00AE3144 BD403E68
80100100
040E0000 00AE3144 1E37D008
20000000
80400100
040E0000 00AE3144 1E27D008
20000000
[/code]
