### ISSUE TITLE
Inf. Zonai Device Duration seems makes rocks durable as well.

### ISSUE THREAD

**Issue by Gameswithjohn** [bad1dea/NXCheats#58]
For some reason after applying the inf. Zonai Device Druation cheat I can't seem to break stones with tools. I tested to make sure it was this mod causing it and after removing this one the rocks were breakable again. Can blow up rocks with bombs still.

**Comment by bad1dea** [comment]
Emulator?

**Comment by hardcorelolz** [comment]
yuzu

**Comment by Gameswithjohn** [comment]
> Emulator?

I'm using Yuzu and have the 1.1.1 patch installed. 

Additionally the "spiderman" cheat doesn't seem to be working.

<img width="458" alt="yuzu Totk properties" src="https://github.com/bad1dea/NXCheats/assets/11891549/092394d9-2eb6-403b-9b5c-3563f228f139">

**Comment by Kazicoon** [comment]
I'm having this same issue, I thought I was doing something wrong lmao

**Comment by Kazicoon** [comment]
> For some reason after applying the inf. Zonai Device Druation cheat I can't seem to break stones with tools. I tested to make sure it was this mod causing it and after removing this one the rocks were breakable again. Can blow up rocks with bombs still.

I've just been using bombs till this is fixed lol

**Comment by bad1dea** [comment]
Test and let me know

**Comment by bad1dea** [comment]
https://github.com/bad1dea/NXCheats/assets/10354814/9f83ff41-a569-4dd8-b2f6-d13c9e352c44

These rocks?

**Comment by Gameswithjohn** [comment]
It was all rocks as well as ore nodes/crates/boxes, any other "breakable" item. Except I think zonite ore for some reason.
