### ISSUE TITLE
Cheat request/fix - Auto Life

### ISSUE THREAD

**Issue by rayne9963** [bad1dea/NXCheats#59]
Inf. Life is basically the same as No Fall Damage imo
Is there way to fix the auto life cheat, which refills hearts when you receive damaged. 

KaitoB 
[Auto Life]
400B0000 00000000 00641D64
680F01B0 34000040 B9401940
400B0000 00000000 00641D6C
640F01B0 00000000 B9000940

Code works on base TOTK, after update, it does not work anymore.

**Comment by bad1dea** [comment]
I’m not KaitoB and I believe he updated his codes already.
