### ISSUE TITLE
Zelda Totk Change speed of Glider Speed (3x)

### ISSUE THREAD

**Issue by seedlord** [bad1dea/NXCheats#61]
```
[#24. Glider Speed (3x) (Hold A)]
040E0000 0381F4EC 3D088889
80000001
040E0000 0381F4EC 3E000000
20000000

```
What do I need to change the speed? 
I want 1.5x instead of 3x. I tried altering 3D088889 and 3E000000 but this does not work as I want.

**Comment by Cr4nkSt4r** [comment]
3D088889 is the default value, 3E000000 is the new value which is getting set on button press.
So you only need to change 3E000000.
Based on khuong, the default speed is 0.0333333.
So you do some math like: 0.0333333 * X (amount of the multiplier you want) = Y =>????????

**4x:** 0.0333333 * 4 = 0,1333332 (0,13 rounded) => **3E051EB8**
**5x:** 0.0333333 * 5 = 0,1666665 (0,17 rounded) => **3E2E147B**
**6x:** 0.0333333 * 6 = 0,1999998 (0,2 rounded) => **3E4CCCCD**

**Comment by seedlord** [comment]
Thanks for your reply.
I managed to set my desired value already (0.05) as you mentioned in hex 3D4CCCCD. 
This seems also to be the speed that Tulins power gives you. 
I changed the hotkey to L Thumb Stick because with "O" it interferes your ultrahand.

```
[#24. Glider Speed (1.5x) (Hold L Stick)]
040E0000 0381F4EC 3D088889
80000010
040E0000 0381F4EC 3d4ccccd
20000000
```
