### ISSUE TITLE
Cant break rocks 

### ISSUE THREAD

**Issue by Kazicoon** [bad1dea/NXCheats#64]
When I have any of these cheats active I cant break rocks, I can use bombs to break them but when I try to use a hammer it just won't break

**Comment by hardcorelolz** [comment]
Same issue

**Comment by Kazicoon** [comment]
> Same issue

Turn off infinite Zonai device duration, until that gets fixed you can't break rocks with a weapon, you'll need bombs otherwise if you want the zonai device duration turned on

**Comment by bad1dea** [comment]
I think this is fixed.. Open a new issue if its not.
