### ISSUE TITLE
[TOTK] Invincible makes zonai device can't stop

### ISSUE THREAD

**Issue by FYWinds** [bad1dea/NXCheats#65]
### Environment
Emulator: Yuzu 1436
TOTK Version: 1.1.1
Mods version: f15e9ff

### Problem
When invincible is enabled, all zonai devices are not able to hit the second time. They can only take 1 hit and the following hits will be useless. Both melee and arrow won't hit.

**Comment by bad1dea** [comment]
Is this still an issue?

**Comment by FYWinds** [comment]
I tried with code of fe7e866 and yuzu 1445
seems good now
