### ISSUE TITLE
Pickup x2, x4, x10 no longer apply to Poe or Zonai devices

### ISSUE THREAD

**Issue by Letrico** [bad1dea/NXCheats#70]
Environment
CFW
TOTK Version: 1.1.1
https://github.com/bad1dea/NXCheats/commit/3b718a40414130988579471868010e5514ecb0aa

Pickup used to work for any items after the first pickup in the version that have pickup/sell/buy. With the new version of the code, it no longer affect Poe or Zonai devices that come out form the dispenser.

**Comment by epl609** [comment]
Truth. I also have to reboot the game when turning the code on or off for it to work.

**Comment by col82293** [comment]
arrows no longer multiply either

**Comment by bad1dea** [comment]
I'll be updating codes shortly :) most likely today: D
