### ISSUE TITLE
I can't disable movement speed cheat?

### ISSUE THREAD

**Issue by chromatic91** [bad1dea/NXCheats#71]
Hello!
I'm trying to remove the movement speed cheat, i tried deleting the addon, but that didnt work, so then i tried the x1 version, but that didn't work either.

So now Link is zooming around at insane speeds and i cant slow him down.
Any tips?

[EDIT]
Turns out having attack speed 1.5x multiplies your movement speed as well. Weird. Bug?

**Comment by TehChozinOne** [comment]
It has been reported https://github.com/bad1dea/NXCheats/issues/68

**Comment by chromatic91** [comment]
Ah, i missed that one! Closing the thread
