### ISSUE TITLE
inf. zonai device duration (no blink + despawn) crashing game when activated

### ISSUE THREAD

**Issue by DontJumper** [bad1dea/NXCheats#72]
Game version: 1.1.1
Playing on nintendo switch 

Game is crashing instantly when this option is turned on, with other cheats on or alone

**Comment by bad1dea** [comment]
You can at least post logs.. either way redownload and try again.. found why bunch of codes was causing crash -- had bad branch addresses being generated by code changes to scripts.

**Comment by DontJumper** [comment]
> You can at least post logs.. either way redownload and try again.. found why bunch of codes was causing crash -- had bad branch addresses being generated by code changes to scripts.

Sure mate, wouldve gladly done it if i knew where to find it. Thanks for updating
