### ISSUE TITLE
Cheats don't work

### ISSUE THREAD

**Issue by NoAvalaibleNames** [bad1dea/NXCheats#73]
I don't know what I do wrong, but I can't get those cheats to work. I have Ryujinx,  game 1,1,0 and following those steps:
1. Unpack cheats folder from package for Ryujinx
2. Right click on the game and click Open mod directory
3. Copy cheats folder there
4. Right click on the game and click Manage cheats
5. Select desired cheats
6. Start game

**Comment by chromatic91** [comment]
Switching to 1.1.1 solved this problem for me. Are you sure you're using the right patch for the cheats?
