### ISSUE TITLE
Game Not Launching

### ISSUE THREAD

**Issue by jashoewa** [bad1dea/NXCheats#75]
Game: TotK
Game version: 1.1.1
Platform: Yuzu EA 3607

When having the cheat "Ignore Cold & Freeze Effects" enabled the game does not launch, it just sticks at black screen.

**Comment by bad1dea** [comment]
You can at least post logs.. either way redownload and try again.. found why bunch of codes was causing crash -- had bad branch addresses being generated by code changes to scripts.
