### ISSUE TITLE
No Cheats Loaded!

### ISSUE THREAD

**Issue by darkxellos** [bad1dea/NXCheats#76]
I updated my tears of the kingdom game, then i grabbed the latest version of the cheat file, i placed it in Atmosphere/contents/gameID/cheats/cheat file i load my game using tesla and it says no cheats loaded....not sure what im doing wrong but any help is greatly appreciated thank you!!!!

**Comment by bad1dea** [comment]
paste your folder struct

**Comment by darkxellos** [comment]
G/atmosphere/contents/0100F2C0225B6000/cheats/168DD518D925C7A3
![totk](https://github.com/bad1dea/NXCheats/assets/134475030/1898269f-0c75-45a8-ae8c-2c01c55b4fa6)
