### ISSUE TITLE
Infinite Materials Bug

### ISSUE THREAD

**Issue by Graadul** [bad1dea/NXCheats#77]
Yuzu 1441; TOTK ver. 1.1.1; Infinite Materials bug:
If  in hands 5 mats and in invertory was 35 (for exmpl), then after drop 5 mats from hands to the ground other materials will disappear from inventory.

**Comment by 2ndHouse** [comment]
Yeah I'm having some weird behavior with that code too. I attach an item to an arrow and shoot, it shows I have a crazy high number of said item, like hundreds of thousands. Eventually the item shows up in the inventory as having 999.

Dropping items seems very buggy, I've dropped one of an item when I have multiple and it completely takes away the item in the inventory (have 0 of that item left).

Also tried eating a regular apple and the game locked up, had to restart Yuzu. For now, I think the Infinite Materials code is a little too buggy to use safely.

**Comment by bad1dea** [comment]
Please post the code you're using..

**Comment by 2ndHouse** [comment]
> Please post the code you're using..

I'm using Yuzu EA 3609
TOTK version 1.1.1
#35 Inf. Materials cheat

**Comment by bad1dea** [comment]
I change the codes randomly, you need to paste the exact one you're having issue with so I can see..

I also don't use emulators so I don't test them on Emu's

**Comment by 2ndHouse** [comment]
It was this one:

https://github.com/bad1dea/NXCheats/tree/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom/0100F2C0115B6000%20v196608%20for%20Yuzu/%2336.%20Inf.%20Material(s)/cheats

**Comment by bad1dea** [comment]
Thanks I think I know the issue I should have done something else but I went the easy route I’ll change it tomorrow

**Comment by 2ndHouse** [comment]
Tried the updated cheat and it works for eating (as description says) but not other materials. Was hoping to have unlimited materials mostly for arrows like bombs and fire. I'm guessing doing that makes the cheat to buggy? Would a max items cheat work better (giving 999 all the time)?

Also have a question about this food items cheat:
https://github.com/bad1dea/NXCheats/tree/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom/0100F2C0115B6000%20v196608%20for%20Yuzu/%2334.%20Inf.%20Food%20Items/cheats

What do you do when you are carrying max food items allowed, but you need to make room in bags for a new food item? You can't drop food items like you can materials, so not sure how to go about this.

**Comment by bad1dea** [comment]
I changed how the code works.. :) Open new issue if there's an issue with the new item codes.
