### ISSUE TITLE
New 'Ignore Fall Damage & Reaction' code makes the simulator CTD

### ISSUE THREAD

**Issue by OrangeVillage** [bad1dea/NXCheats#78]
Just like what I said in the title, new 'Ignore Fall Damage & Reaction' code would crush the simulator to desktop after loading any save. Here is my save file.
[slot_00.zip](https://github.com/bad1dea/NXCheats/files/11556134/slot_00.zip)

**Comment by bad1dea** [comment]
You can at least post logs.. either way redownload and try again.. found why bunch of codes was causing crash -- had bad branch addresses being generated by code changes to scripts.
