### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by TARDIS76** [bad1dea/NXCheats#80]
just downloaded the new codes now the game crashes on ryjinxx

**Comment by bad1dea** [comment]
What codes enabled..

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: TARDIS76 ***@***.***>
Sent: Wednesday, May 24, 2023 3:56:38 PM
To: bad1dea/NXCheats ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bad1dea/NXCheats] game crashes (Issue #80)


just downloaded the new codes now the game crashes on ryjinxx

**Comment by TARDIS76** [comment]
god mode
unlimited stamina 

 item multiplier x8

 inf matrials

inf battery

 damage x30

things like that

show all shrines as well

**Comment by bad1dea** [comment]
You can at least post logs.. either way redownload and try again.. found why bunch of codes was causing crash -- had bad branch addresses being generated by code changes to scripts.
