### ISSUE TITLE
Inf. Rupees for Ryujinx platform

### ISSUE THREAD

**Issue by Ecureuilvirtuel** [bad1dea/NXCheats#81]
Hello @bad1dea ,
Could you provide again the cheat for inf. rupees please ?
It's not urgent ;)

The code was :
[[#05. Inf. Rupees]](https://github.com/bad1dea/NXCheats/commit/acf49cb2c70ddded364af07ca0f631c115959685)
040E0000 01E93924 1A9813F6

I don't know if it worked because I'm just arriving in Hurule and Rupees are not yet activated ☺️

Thank's a lot for your work !

**Comment by Graadul** [comment]
> 040E0000 01E93924 1A9813F6
Still working on Yuzu. For both emuls HEX are the same.

**Comment by Ecureuilvirtuel** [comment]
I try on Ryujinx and it's not working anymore, that's why it was removed.

To try, to put this lines in the cheat file under section Inventory :

[#40. Inf. Rupees]
040E0000 01E93924 1A9813F6

And I changed [#40. Map - Show All Shrine Locations]  to [#41. Map - Show All Shrine Locations]

But when I want to buy something in the game, the cheat not working. I've 0 rupees for this moment, maybe in need au minimum 1 rupees ... 🤷‍♂️😅

**Comment by Ecureuilvirtuel** [comment]
> > I try on Ryujinx and it's not working, that's why it was removed.
> > To try, I changes those lines in the cheat file under section Inventory :
> > [#40. Inf. Rupees] 040E0000 01E93924 1A9813F6
> > And I changed also [#40. Map - Show All Shrine Locations] to [#41. Map - Show All Shrine Locations]
> 
> It conflicting with other cheats. Last time it was inf. Ingridients. For now I'm using Inf rup+ inf wep dur + inf zanai device + inf zanai duration + inf amiibo and inf rup working


I uncheck all cheat from Ryujinx interface and I check only Inf. Rupees and it's not working

enabled.txt
168DD518D925C7A3-<#40. Inf. Rupees Cheat>

Normally my enabled.txt is
168DD518D925C7A3-<#03. Inf. Stamina Cheat>
168DD518D925C7A3-<#30. Inf. Equipment Durability (Fire will still break it.) Cheat>
168DD518D925C7A3-<#31. Inf. Arrow(s) Cheat>

And in the same configuration of enabled.txt, Link run very fast, maybe it is the problem of conflict ... 🧐

**Comment by Graadul** [comment]
> > It conflicting with other cheats. Last time it was inf. Ingridients. For now I'm using Inf rup+ inf wep dur + inf zanai device + inf zanai duration + inf amiibo and inf rup working
> 
> I uncheck all cheats from Ryujinx interface and I check only Inf. Rupees and it's not working
> 
> So my new enabled.txt contain 168DD518D925C7A3-<#40. Inf. Rupees Cheat>
> 
> Normally my enabled.txt contain these cheat 168DD518D925C7A3-<#3. Inf. Stamina Cheat> 168DD518D925C7A3-<#30. Inf. Equipment Durability (Fire will still break it.) Cheat> 168DD518D925C7A3-<#31. Inf. Arrow(s) Cheat>
> 
> And in the same configuration of enabled.txt, Link run very fast, maybe it is the problem of conflict ... 🧐

As I noticeds  inf rupees working only when buying smthg in stores. In stables you will still pay for bed, and for armour upgrades too.  Where did you test it?

**Comment by Ecureuilvirtuel** [comment]
> I noticeds that inf rupees working only when buying smthg in stores. In stables you will still pay for bed, and for armour upgrades too. Where did you test it?

I tried in a store but like @bad1dea said :

> I don't even have Inf. Rupees in 1.1.1 cheat right now.. so ya.

**Comment by bad1dea** [comment]
I'll readd Rupee's in a bit./. :)
