### ISSUE TITLE
Ignore Material Requirements for Upgrades (Horse and Armor)

### ISSUE THREAD

**Issue by onetwelve2021** [bad1dea/NXCheats#82]
Crashes when trying to upgrade horses I haven't tried with armors on the Switch

**Comment by bad1dea** [comment]
Paste the exact code from your text file here..

**Comment by onetwelve2021** [comment]
[#39. Ignore Material Requirements for Upgrades (Horse and Armor)]
040E0000 01B108E4 2A1F03E8
040E0000 02054DE8 32000281
040E0000 020595A8 14000014
040E0000 012FF124 6B09013F
040E0000 01A674A0 D503201F
040E0000 01FD0538 D503201F
040E0000 0212CD44 D503201F


Thank you

**Comment by bad1dea** [comment]
Can you test new code, for 1.1.2 and let me know

**Comment by onetwelve2021** [comment]
I just downloaded the latest one and still hangs as soon as you pick enchance a horse.
Thank you

**Comment by bad1dea** [comment]
Send me a save pleas

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by onetwelve2021** [comment]
[The Legend of Zelda  Tears of the Kingdom.zip](https://github.com/bad1dea/NXCheats/files/11580935/The.Legend.of.Zelda.Tears.of.the.Kingdom.zip)

**Comment by onetwelve2021** [comment]
It's my whole jksv back up I cannot tell which one you need so it's my whole save sorry

**Comment by bad1dea** [comment]
Thank you.. I'll take a look!

**Comment by bad1dea** [comment]
Fixed.
