### ISSUE TITLE
Glider Speed (x3) causes Ultrahand Teleport Bug

### ISSUE THREAD

**Issue by GLiTcH2** [bad1dea/NXCheats#83]
So I noticed when you have the Glider Speed cheat active you can not move at all while using Ultrahand to pick up an object if you do this will cause you to teleport/launch. Pretty easy to reproduce just move in any direction, Use ultrahand and tap A to pickup an object while moving. With Glider Speed disabled you can run/move and pickup objects without getting launched!

https://github.com/bad1dea/NXCheats/assets/19172857/d76c8d10-eac0-47c8-baac-45367da2aa98

**Comment by bad1dea** [comment]
Yeah, you should change the hotkey from A.. 

I'll put a asm code one in stead..

**Comment by seedlord** [comment]
use this for 1.5 speed and L Stick for Glider Speed. see [#61](https://github.com/bad1dea/NXCheats/issues/61)
```
[#24. Glider Speed (1.5x) (Hold L Stick)]
040E0000 0381F4EC 3D088889
80000010
040E0000 0381F4EC 3d4ccccd
20000000
```

**Comment by GLiTcH2** [comment]
> use this for 1.5 speed and L Stick for Glider Speed. see [#61](https://github.com/bad1dea/NXCheats/issues/61)
> 
> ```
> [#24. Glider Speed (1.5x) (Hold L Stick)]
> 040E0000 0381F4EC 3D088889
> 80000010
> 040E0000 0381F4EC 3d4ccccd
> 20000000
> ```

Thanks for the code, However 1.5 speed is a little too slow for me. The 3x speed for me feels just right since it's not too fast but not slow either, However I did copy the L stick part of the code so that at least I can use Ultrahand without getting thrown all over the place! Tho the only downside with L stick is that's the button for crouch so if you are moving and crouch it tends to launch you forward fast but I hardly ever use crouch and as long as I am not moving it wont launch me.

**Comment by dpyron325** [comment]
> Yeah, you should change the hotkey from A..
> 
> I'll put a asm code one in stead..

have u gotten a chance to fix this yet?

**Comment by bad1dea** [comment]
It's a side effect, either change hotkey or try something else.

**Comment by ShadowOne333** [comment]
What about D-Pad Down?
From what I know it's only used for calling the horse when on foot, but while gliding it doesn't have any use, does it?

**Comment by Ashuraman666** [comment]
I also noticed that you can't turn this cheat off. I turned it off and enabled the restore code and now the effect is permanent without needing to hold A to activate it. So I always long jump, always teleport with the ultrahand, all of that is permanent until I turn the cheat back on

**Comment by cufish** [comment]
> 

You can easily change binds yourself with https://github.com/DarkFlare69/AMS-Cheat-Button-Assigner/releases/tag/1.0

**Comment by dpyron325** [comment]
> > 
> 
> You can easily change binds yourself with https://github.com/DarkFlare69/AMS-Cheat-Button-Assigner/releases/tag/1.0

tyvm for this :)

**Comment by Suffice** [comment]
I rebound the button to X with the Breeze homebrew app.
Upon landing from the air it lets you super jump.
Much better than A.
