### ISSUE TITLE
Inf. Zonai devices and arrow

### ISSUE THREAD

**Issue by Graadul** [bad1dea/NXCheats#84]
> [#32. Inf. Zonai Devices]
> 040E0000 01A75934 2A1F03E1

Yuzu: 1445; TOTK: 1.1.1

After shooting an arrow that has been fused with a Zonai device (rocket for example), the quntity of devices is reduced.

**Comment by bad1dea** [comment]
Codes only for pulling out of inventory.. no fusing.
