### ISSUE TITLE
Inf. Zonai Devices does not work when 1 Zon Dev left

### ISSUE THREAD

**Issue by Graadul** [bad1dea/NXCheats#86]
> [#32. Inf. Zonai Devices]
> 040E0000 01A75934 2A1F03E1
YUZU: 1446; TOT: 1.1.1

When you drop the last zonai device, the cheat does not work and the device disappears from the inventory

**Comment by bad1dea** [comment]
Normal, you need at least 2 in inventory -- just dupe it, drop one, pick up, etc.
