### ISSUE TITLE
Create 998 cheat and Korok Location

### ISSUE THREAD

**Issue by Dinfevo** [bad1dea/NXCheats#89]
You can create a 998 cheats for Material, arrows and devices.
Also if you can create a Korok Location cheat would be awesome.

**Comment by bad1dea** [comment]
> You can create a 998 cheats for Material, arrows and devices. Also if you can create a Korok Location cheat would be awesome.

I had all the map unlocks, like KaitoB does, but the Korok one only shows up while Zoomed in, I'll take a look and see if KaitoB does it differently..

**Comment by GLiTcH2** [comment]
> You can create a 998 cheats for Material, arrows and devices

You could use this Save Editor: https://www.marcrobledo.com/savegame-editors/zelda-totk/ it allows you to give yourself 999 of anything in your inventory and a lot of other things can also be edited as well.

**Comment by bad1dea** [comment]
I made a 500x highlight any item in inventory, and it'll set it to 500 if there's less than 500.. (for mateirals and zonai devices)

I'll make it so it sets to 500 from like the DPAD menu later.

**Comment by bad1dea** [comment]
I changed the code, so now its a minimum of it.
