### ISSUE TITLE
Cheats broke after ryujinx update to 1.1.744

### ISSUE THREAD

**Issue by StanTheRebel** [bad1dea/NXCheats#9]

**Comment by NinomaeTakonis** [comment]
Can confirm. Unfortunate as these were the only functional cheats on Ryujinx.

**Comment by StanTheRebel** [comment]
hoping new codes are found because i suck so bad lol

**Comment by bad1dea** [comment]
Has nothing to do with the codes, Ryujinx changed something on their end. Post an issue on Ryujinx Github..
