### ISSUE TITLE
How do I know what version is what?

### ISSUE THREAD

**Issue by paperc07** [bad1dea/NXCheats#90]
I got all the cheats, 
<img width="366" alt="image" src="https://github.com/bad1dea/NXCheats/assets/9095222/cd85f9b3-d554-4b20-87e9-d6c54d585d42">

but I don't know what's what im currently on 1.1.0 debating if I should go to 1.1.1 or 1.1.2

**Comment by bad1dea** [comment]
BUILDIS is the version... but my ryujinx has multiple versions, and it'll read it off whatever build you're using..

**Comment by paperc07** [comment]
so what do I need to do? I am so lost, do I delete everything and update to the latest version and just try then? but which file do I get, this is all so confusing

**Comment by FikaCode** [comment]
what's differents 262144 and 196608  ?

**Comment by paperc07** [comment]
Yeah I figured it out didn't know I had to find the title Id of the downloaded file. But I got it sorted thanks

**Comment by bad1dea** [comment]
196 = 1.1.1
262 = 1.1.2

**Comment by FikaCode** [comment]
> 196 = 1.1.1 262 = 1.1.2

Thanks.
