### ISSUE TITLE
Not use  "/" in cheat name

### ISSUE THREAD

**Issue by abossd** [bad1dea/NXCheats#93]
for exzample
[#38a Item Pickup/Sell/Buy Multiplier (2x)/cheats]
will make 7z for yuzu
#38a Item Pickup   
Sell 
Buy Multiplier (2x)
3 floders 

0100F2C0115B6000 v262144 for Yuzu.7z\0100F2C0115B6000 v262144 for Yuzu\#38a Item Pickup\Sell\Buy Multiplier (2x)\cheats

**Comment by bad1dea** [comment]
That makes sense.. Thanks! Edited the script for future code runs.
