### ISSUE TITLE
Instant companion cheat not working. 

### ISSUE THREAD

**Issue by abaresaru** [bad1dea/NXCheats#95]
It seems the instant companion cheat doesn’t work on yuzu TotK 1.10  

shown as installed and active but companions still have cool-down timers.

**Comment by bad1dea** [comment]
I tested it, and it's working fine, on 1.1.2 and 1.1.1 

I no longer support 1.1.0 please update

**Comment by abaresaru** [comment]
Ahh. Sorry my misunderstanding. Thought mods worked backwards with previous versions. Just not with new versions. 

Thanks for taking the help. Shall go ahead and update.
