### ISSUE TITLE
720p docked vs 540p docked

### ISSUE THREAD

**Issue by Graadul** [bad1dea/NXCheats#96]
TOTK 1.1.1 YUZU 1448
720p docked and 1.5x render scale (1080p result):

> [#42f Docked 720p]
> 580F0000 047215A0
> 580F1000 00000090
> 780F0000 000000F0
> 680F01D0 00000360 00000600

![720p](https://github.com/bad1dea/NXCheats/assets/45491326/629b5cb7-303a-4690-bcce-a1c4a8259737)

540p docked (not from this cheat compilation) and 2x render scale (1080p result):

> [Docked 540p]
> 580F0000 04719670
> 580F1000 00000090
> 780F0000 000000F0
> 680F01D0 00000288 00000480

![540p](https://github.com/bad1dea/NXCheats/assets/45491326/6267a2fe-3a49-4d25-abe1-50c5cb3b62a4)

After scaling 540p gives better quality than 720p. Both without AO loosing.

**Comment by bad1dea** [comment]
Do you want me to add this?

**Comment by Graadul** [comment]
> Do you want me to add this?

I think 720p cheat doesn't work. if the cheat worked then images would be the same quality. But with 720p cheat game still running in 900p.
And you can add 540p to your collection. But I do not know is it compatible with TOTK 1.1.2.

**Comment by bad1dea** [comment]
I'm not 100% sure it does anything, it's very minuscule differences -- I'm by no means an expert changing graphic settings on the switch.

But I do know switching it does effect clarity, I've compared them to the exefs patches, and they are similar.

540p vs 720p is a huge leap, your screenshots don't do it justice

540p
![image](https://github.com/bad1dea/NXCheats/assets/10354814/df2bc8ec-cdee-4a4f-bfb3-3f7e7452bab8)

720p
![image](https://github.com/bad1dea/NXCheats/assets/10354814/ad0b666b-da9d-4654-a1a5-7247dfda8386)

**Comment by bad1dea** [comment]
You can tell by the little details in mini map.

**Comment by Graadul** [comment]
> I'm not 100% sure it does anything, it's very minuscule differences -- I'm by no means an expert changing graphic settings on the switch.
> 
> But I do know switching it does effect clarity, I've compared them to the exefs patches, and they are similar.
> 
> 540p vs 720p is a huge leap, your screenshots don't do it justice
> 
> 540p ![image](https://user-images.githubusercontent.com/10354814/241576586-df2bc8ec-cdee-4a4f-bfb3-3f7e7452bab8.png)
> 
> 720p ![image](https://user-images.githubusercontent.com/10354814/241576597-ad0b666b-da9d-4654-a1a5-7247dfda8386.png)

In yuzu by clicking with RMB on TOTK,  open Properties - Adv.Graphics - Resolution. There you can set 2x (or 4x) for 540 and see how it changed then 1.5x for 720p.
You can compare quality with 720p cheat and without it. Game alwais runs in 900p (if resolution cheat/mod not working) no matter what resolution selected in advanced graphical options.

**Comment by bad1dea** [comment]
Oh… you’re talking about the emulator.

Yeah those codes are for switch hardware. I have to do sdk stuff for emulators which I have no desire too.

I believe there are exefs patches that work on the emus on gba.
