### ISSUE TITLE
Alternate Infinite Materials code that excludes fairies

### ISSUE THREAD

**Issue by 2ndHouse** [bad1dea/NXCheats#97]
Using your new Infinite Materials code found here:

https://github.com/bad1dea/NXCheats/blob/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom/0100F2C0115B6000%20v196608%20for%20Yuzu/%2337.%20Inf.%20Materials%20%26%20Zonai%20Devices%20(Set%20To%20Minimum%20Qty.500)/cheats/168DD518D925C7A3.txt

It's working great so far and seems like a good way to handle infinite materials, but having infinite fairies is way too game breaking for my taste. Wondering if it's possible to create an alternate version of the code that excludes fairies and just keeps them at the original number I have?

**Comment by bad1dea** [comment]
Can you show me.. where they are located in inventory? (Picture) + Where to find them?

**Comment by 2ndHouse** [comment]
Hm, well I'm using a sorting mod and it puts them as the first thing in my bag when sorted by type. Does that mod matter for what you need? Currently, I decided to remove them from my bags using the online save editor as it was just too game breaking, infinite lives pretty much.

As for where to find them, do you mean in-game? I haven't came across many, but they seem to be in some wells and caves.

**Comment by bad1dea** [comment]
Just need the picture.. :) I don't play the game, so I'll have to add it to inventory.

**Comment by 2ndHouse** [comment]
Well I'm currently not at the PC with the game, but here is a screenshot showing the item in the save editor, which seems to use the same icons. If this doesn't help, I will get an in-game screenshot later today.

[https://imgur.com/a/1nscBQ3](url)

**Comment by bad1dea** [comment]
No rush. Not sure I'll be able to filter it out since I just do a filter on Material / Zonai Devices vs Weapon/Shield/KeyItems.

What I can probably do is.. :P make a seperate code that sets faries to something less.. lol

**Comment by 2ndHouse** [comment]
Would the in-game screenshot still be helpful then?

Not sure having less fairies would really help the problem. Having just one infinite fairy is too much, they resurrect you upon death. If possible, need a way to keep fairies as the game intended, only having a finite amount available. Your code is great for having infinite fire arrows for example, but with fairies being infinite too it becomes infinite materials and infinite lives rolled into one.

Also just wanted to say thanks for the work your doing! I like to use codes to save time on tedious tasks in open world games and your codes really help.

**Comment by 2ndHouse** [comment]
OK was able to get a screenshot in-game. The fairy is highlighted in the top left:

https://imgur.com/a/IGeFRZX

**Comment by bad1dea** [comment]
Too complicated to do, with asm..

You can use Eiffels code that ads/removes items from inventory..
