### ISSUE TITLE
Request: Superspeed (x2) holding ZL

### ISSUE THREAD

**Issue by ThePapaw** [bad1dea/NXCheats#98]
I had found a cheat mod for v1.1.1 that would do this, SuperSpeed (x2) when you held ZL. Not sure who made it. Are you able to make one for v1.1.2?

Is it hard to make these?

I apologize if you don't do requests and thank you for your time either way

**Comment by Duhhmas** [comment]
If you still have the  SuperSpeed cheat, and it works the same as this one, then you can copy+paste the SuperSpeed code into the txt file for this cheat.
